---

- name: Add user group "{{ docker_compose_user_group }}"
  group:
    name: '{{ docker_compose_user_group }}'

- name: Add user "{{ docker_compose_user }}"
  user:
    name: '{{ docker_compose_user }}'
    group: '{{ docker_compose_user_group }}'
    home: '/home/{{ docker_compose_user }}'
    shell: /bin/bash

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: true
  loop:
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Install docker & docker-compose
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: true
    force: yes
  loop:
    - docker-ce=5:26.1.2-1~ubuntu.22.04~jammy
    - docker-compose=1.29.2-1

- name: Start service docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: '{{ docker_compose_user }}'
    groups: docker
    append: yes

- name: Start Docker-compose
  block:

    - name: Build .env file
      template:
        src: '.env.j2'
        dest: '{{ docker_compose_dir }}/{{ docker_compose_env_target_file }}'
        owner: '{{ docker_compose_user }}'
        group: '{{ docker_compose_user_group }}'
        mode: '0644'
      when: docker_compose_env | default([], true) | length > 0

    - name: Copy docker-compose file
      copy:
        src: '{{ docker_compose_file }}'
        dest: '{{ docker_compose_dir }}/docker-compose.yml'
        owner: '{{ docker_compose_user }}'
        group: '{{ docker_compose_user_group }}'
        mode: '0644'

    - name: Copy extra files
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: '{{ item.owner | default(docker_compose_user) }}'
        group: '{{ item.group | default(docker_compose_user_group) }}'
        mode: '0644'
      loop: '{{ docker_compose_extra_files }}'
      when: docker_compose_extra_files | default([], true) | length > 0

    - name: Run commands
      shell: '{{ item }}'
      loop: '{{ docker_compose_run_commands }}'
      when: docker_compose_run_commands | default([], true) | length > 0

    - name: Build and start containers
      become: true
      docker_compose:
        project_src: '{{ docker_compose_dir }}'
        state: present
        files:
          - docker-compose.yml

  when: docker_compose_file | default('', true) != ''
